theme: jekyll-theme-primer
title: Spotify Data Analysis
description: Creating the Best Playlist
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
